version: 0.9.0-{build}
os: Visual Studio 2017
configuration: Release
before_build:
- dotnet restore
build_script:
- dotnet pack src/JohnKnoop.MongoRepositor/ -c %CONFIGURATION%
artifacts:
- path: src/JohnKnoop.MongoRepository/bin/Release/*.nupkg
  name: nuget
